server:
  port: 8082
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weatherdb
    username: root
    password: root     
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect